### ISSUE TITLE
python script/create-index.py ValueError: No such layer: flatten_1

### ISSUE THREAD

**Issue by erphao** [yoheikikuta/trademark-retrieval#4]
where is 'flatten_1' define?

**Comment by yoheikikuta** [comment]
`flatten_1` is the name of a Fatten layer in Keras ResNet50.
I'm not sure the reason of the error. Did you use the Dockerfile in the repo? If so, maybe the versions of tensorflow/keras are problematic (I only run the scripts with quire old versions).

**Comment by erphao** [comment]
tensorflow           1.14.0 
Keras                2.2.4  
Keras-Applications   1.0.8

**Comment by erphao** [comment]
It looks good.
i changed the version
Keras               2.2.2  
Keras-Applications  1.0.4  
Keras-Preprocessing 1.0.2 
tensorflow          1.10.0

**Comment by yoheikikuta** [comment]
Thanks for checking!!
I'd appreciate it if you could send me a PR to fix the versions.

**Comment by yoheikikuta** [comment]
Fixed: https://github.com/yoheikikuta/trademark-retrieval/commit/c8857a764aa16f20a3dcee3bc93e91093d7fa3d6.
Thanks for reporting the bug!
